# Numpy Introduction

In [1]:

pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [27]:
a= np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [23]:
a2=a[np.newaxis,:]
print(a2)
a2.shape


[[0 1 2 3 4 5]]


(1, 6)

In [36]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

---

# Creating Arrays with Numpy

In [51]:
a= np.array([1,2,3,4,5,6,7])

b= np.array([(1,2,3,4,5,6,7) , (4,5,6,7,8,9,10)])

In [56]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [100]:
len(a)

7

In [54]:
print(b)

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


In [101]:
len(b)

2

In [52]:
b.shape

(2, 7)

# Initialize the arrays

In [70]:
zeros =np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
ones =np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
full=np.full((6,8) , 10)


In [107]:
len(full)

6

In [99]:
type(full)

numpy.ndarray

In [90]:
full.dtype

dtype('float64')

In [80]:
print(full)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


In [77]:
full

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [116]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [111]:
a

b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [115]:
z=a+b
z

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [120]:
z=a*b
(z)

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])