In [54]:
import numpy as np

In [55]:
empty=np.empty((3,4))
print(empty)
print("--------------------")
print(empty[1])

[[1.00159613e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 4.47032019e-038 4.46438810e-090 1.14349539e-071]
 [5.54403636e+169 4.12135137e-033 3.99910963e+252 8.32945485e-071]]
--------------------
[1.11260619e-306 4.47032019e-038 4.46438810e-090 1.14349539e-071]


In [56]:
x= np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [57]:
odd= np.arange(1,23,2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [61]:
df=np.arange(0,23,24)
df

array([0])

In [70]:
a=np.array([0,1,2,3,4,5])
b=np.array([6,7,8,8.,9,10])


In [71]:
c=np.concatenate((a,b))
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  8.,  9., 10.])

In [87]:
# create 3D array of size 
a1=np.array([[[0,1,2,3]],
            [[4,5,6,7]],
            [[0,1,2,3]]])
a1.shape

(3, 1, 4)

In [89]:
a3 =a1.reshape(6,2)
a3.shape

(6, 2)

In [90]:
# reshape the a 
a=a.reshape(2,6)
a.shape
a

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 0, 1, 2, 3]])

In [91]:
a=np.array([1,2,3,4,5])
a.shape

(5,)

In [94]:
a[np.newaxis,:].shape

(1, 5)

## Video NO-3

# Numpy Indexing and Slicing

In [2]:
import numpy as np

In [12]:
# Create an array
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a[0]

1

In [15]:
b=np.arange(0,12,2)
b


array([ 0,  2,  4,  6,  8, 10])

In [34]:
c=b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [33]:
c[1]

array([False, False, False])

In [37]:
c[c>5]

array([ 6,  8, 10])

# Enlist boolean ops

# Making an array from a data or another array

In [42]:
a=np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [44]:
len(a)

45

In [45]:
array1=a[40:45]
array1

array([200, 205, 210, 215, 220])

In [68]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [69]:
c=np.hstack((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
d=np.vstack((a,b))
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
d= d.reshape(5,2)
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

----
# Matrix or Matrices

In [87]:
# Creating a 2x3 matrix
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
# Create a matrix of big dimension
b=np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [128]:
b.max()

98

In [127]:
b.min(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [122]:
# Slicing the matrix
c=b[1:3 , 3:5]